### ISSUE TITLE
Sleeper Channel Addition

### ISSUE THREAD

**Issue by TommyGuns012** [StoneMasons4106/sleeper-ffl-discordbot#1]
Wondering if you can add slash command to get Sleeper Channel Notifications directly to discord

**Comment by StoneMasons4106** [comment]
> Wondering if you can add slash command to get Sleeper Channel Notifications directly to discord

You're referring to the league chat basically duplicating itself into a discord channel correct? If so, right now the only documentation on the Sleeper API is only available through get requests, and it says nothing about the League Chat. See here: https://docs.sleeper.app/

It's a fantastic idea though, I'll see if I can reach out and see if they make that available through webhook functionality or something to that effect.

**Comment by StoneMasons4106** [comment]
From the Sleeper team: Hi there, they are not. Sorry about that, but will definitely pass it to the team!

Closing this as this feature is not yet available.

**Comment by StoneMasons4106** [comment]
From the Sleeper team: Hi there, they are not. Sorry about that, but will definitely pass it to the team!

Closing this as this feature is not yet available.

**Comment by TommyGuns012** [comment]
not quite league chat, but more so, the public channels on their page. IE: https://sleeper.app/channels/170000000000000000

such as their headlines, not the actual chat associated with it. the breaking news, the injuries, etc.

**Comment by StoneMasons4106** [comment]
> not quite league chat, but more so, the public channels on their page. IE: https://sleeper.app/channels/170000000000000000
> 
> such as their headlines, not the actual chat associated with it. the breaking news, the injuries, etc.

Oh I see. That would be interesting. 

I asked again about this specific use case, but I don't see any webhook documentation from Sleeper's end, their API is pretty basic. Discord would be easy to set this up through but I think the limitation here is on Sleeper, and their dev team would have to set up the functionality first.

I'll post their reply here when they get back.

**Comment by TommyGuns012** [comment]
Great stuff. Thanks for the quick response.

**Comment by StoneMasons4106** [comment]
We actually have a discord server that should pull our alerts. Maybe that might be of help!
﻿https://discord.gg/aP5NH2F7
﻿
﻿Going to do research as to how these notifications get sent

**Comment by StoneMasons4106** [comment]
> Great stuff. Thanks for the quick response.

So my conclusion is that following those channels in the discord server link I sent above is the only way to get these notifications in discord. I think that bot must be created by the guys at Sleeper itself because there is zero public documentation on how to get this type of information yourself. If you have webhook permissions to the server you're looking to set it up on, following those channels will give you live updates like the Sleeper app will.

I'll keep an eye out for if they make this publicly accessible but for the moment, it looks like this is the only way to get this functionality in discord. I've also added this suggested setup as an optional step in the instructions in Github should others be interested. I set it up on mine myself.
